ALTER TABLE products ADD COLUMN IF NOT EXISTS brand text NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS stock integer NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS sort_order integer NOT NULL DEFAULT 0;
