ALTER TABLE "products"
ADD COLUMN IF NOT EXISTS "brand" text DEFAULT '' NOT NULL;

ALTER TABLE "products"
ADD COLUMN IF NOT EXISTS "stock" integer DEFAULT 0 NOT NULL;

ALTER TABLE "products"
ADD COLUMN IF NOT EXISTS "sort_order" integer DEFAULT 0 NOT NULL;
